version: '3'

volumes: # dbマウント
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/product-register'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true # -tと同じ
    stdin_open: true # -iと同じ
    depends_on:
      - db # dbを作ってから
    links:
      - db # webからdbにアクセスできる様になる
  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
